In [1]:
from pandas import *
from numpy import *

In [5]:
df = read_csv("weather_2012.csv")

In [5]:
df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [20]:
df['Stn Press (kPa)'].sum()

887637.46

In [21]:
df['Date/Time'] = to_datetime(df['Date/Time'])

In [22]:
df['Date/Time'].head()

0   2012-01-01 00:00:00
1   2012-01-01 01:00:00
2   2012-01-01 02:00:00
3   2012-01-01 03:00:00
4   2012-01-01 04:00:00
Name: Date/Time, dtype: datetime64[ns]

In [24]:
 df['Weather']

0                        Fog
1                        Fog
2       Freezing Drizzle,Fog
3       Freezing Drizzle,Fog
4                        Fog
                ...
8779                    Snow
8780                    Snow
8781                    Snow
8782                    Snow
8783                    Snow
Name: Weather, Length: 8784, dtype: object

In [28]:
df.drop_duplicates(subset=['Weather'],keep='first')

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
16,2012-01-01 16:00:00,2.6,-0.2,82,13,12.9,99.93,Mostly Cloudy
17,2012-01-01 17:00:00,3.0,0.0,81,13,16.1,99.81,Cloudy
18,2012-01-01 18:00:00,3.8,1.0,82,15,12.9,99.74,Rain
22,2012-01-01 22:00:00,4.4,1.9,84,24,19.3,99.32,Rain Showers
36,2012-01-02 12:00:00,1.7,-6.2,56,48,24.1,99.21,Mainly Clear
41,2012-01-02 17:00:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
55,2012-01-03 07:00:00,-14.0,-19.5,63,19,25.0,100.95,Snow
67,2012-01-03 19:00:00,-16.9,-24.8,50,24,25.0,101.74,Clear
153,2012-01-07 09:00:00,-6.1,-8.7,82,7,9.7,100.15,"Freezing Rain,Fog"
154,2012-01-07 10:00:00,-5.7,-8.0,84,7,8.0,100.13,Freezing Rain
155,2012-01-07 11:00:00,-5.4,-7.7,84,9,9.7,100.08,Freezing Drizzle
221,2012-01-10 05:00:00,0.8,-1.2,86,30,9.7,100.02,"Rain,Snow"
279,2012-01-12 15:00:00,-5.2,-7.6,83,26,0.8,99.90,Moderate Snow
291,2012-01-13 03:00:00,-4.5,-6.9,83,19,4.8,99.19,"Freezing Drizzle,Snow"
297,2012-01-13 09:00:00,-5.0,-7.3,84,32,4.8,98.56,"Freezing Rain,Snow Grains"
309,2012-01-13 21:00:00,-4.8,-7.9,79,37,4.8,99.09,"Snow,Blowing Snow"
510,2012-01-22 06:00:00,-19.0,-22.9,71,6,0.8,102.85,Freezing Fog
516,2012-01-22 12:00:00,-11.5,-15.4,73,9,8.0,102.97,Haze
546,2012-01-23 18:00:00,3.0,1.2,88,19,4.0,100.54,"Rain,Fog"
548,2012-01-23 20:00:00,2.9,1.2,89,26,9.7,100.32,"Drizzle,Fog"
549,2012-01-23 21:00:00,3.3,1.7,89,24,11.3,100.22,Drizzle
755,2012-02-01 11:00:00,-5.8,-8.3,82,9,4.0,100.36,"Freezing Drizzle,Haze"
758,2012-02-01 14:00:00,-4.9,-7.4,83,9,2.0,100.34,"Freezing Rain,Haze"
761,2012-02-01 17:00:00,-4.3,-7.1,81,0,6.4,100.61,"Snow,Haze"
983,2012-02-10 23:00:00,-0.9,-2.4,90,6,9.7,100.76,"Snow,Fog"
1492,2012-03-03 04:00:00,0.3,-1.7,86,24,11.3,99.40,"Snow,Ice Pellets"
1735,2012-03-13 07:00:00,4.0,1.0,81,11,9.7,100.61,"Rain,Haze"
3500,2012-05-25 20:00:00,21.3,18.3,83,13,16.1,100.83,"Thunderstorms,Rain"
3580,2012-05-29 04:00:00,11.4,7.0,74,30,24.1,100.34,"Thunderstorms,Rain Showers"
3582,2012-05-29 06:00:00,10.9,9.0,88,9,2.4,100.26,"Thunderstorms,Heavy Rain Showers"
4323,2012-06-29 03:00:00,19.5,16.1,81,7,9.7,99.71,"Thunderstorms,Rain Showers,Fog"
4456,2012-07-04 16:00:00,26.7,20.1,67,15,24.1,99.84,Thunderstorms
4757,2012-07-17 05:00:00,20.6,18.6,88,19,4.8,100.08,"Thunderstorms,Rain,Fog"
4758,2012-07-17 06:00:00,19.6,18.5,93,15,3.2,100.01,"Thunderstorms,Moderate Rain Showers,Fog"
7035,2012-10-20 03:00:00,12.8,12.1,96,13,6.4,99.83,"Rain Showers,Fog"
7400,2012-11-04 08:00:00,2.2,-1.2,78,17,24.1,101.11,"Rain Showers,Snow Showers"
7887,2012-11-24 15:00:00,0.7,-6.4,59,35,2.4,99.70,Snow Pellets
8229,2012-12-08 21:00:00,0.8,0.3,96,9,6.4,100.73,"Rain,Snow,Fog"
8264,2012-12-10 08:00:00,1.7,0.8,94,17,6.4,99.98,"Moderate Rain,Fog"
8427,2012-12-17 03:00:00,-2.6,-3.7,92,28,8.0,100.95,"Freezing Rain,Ice Pellets,Fog"
8433,2012-12-17 09:00:00,0.4,-0.7,92,20,4.0,100.79,"Drizzle,Ice Pellets,Fog"
8439,2012-12-17 15:00:00,0.9,0.2,95,19,11.3,100.63,"Drizzle,Snow"
8453,2012-12-18 05:00:00,0.6,-0.6,92,24,9.7,100.12,"Rain,Ice Pellets"
8469,2012-12-18 21:00:00,1.0,0.6,97,13,3.2,99.58,"Drizzle,Snow,Fog"
8520,2012-12-21 00:00:00,1.9,-2.1,75,26,25.0,100.60,"Rain,Snow Grains"
8521,2012-12-21 01:00:00,1.1,-0.7,88,17,6.4,100.47,"Rain,Snow,Ice Pellets"
8649,2012-12-26 09:00:00,-11.3,-12.7,89,15,4.0,102.52,"Snow Showers,Fog"
8674,2012-12-27 10:00:00,-5.4,-6.4,93,41,0.6,100.64,"Moderate Snow,Blowing Snow"

In [29]:
df

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [67]:
df['Weather'].nunique()

50

In [4]:
arr=df['Weather'].unique()

In [34]:
arr

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [8]:
arr.shape

(50,)

In [35]:
arr.size

50

In [37]:
df['Wind Spd (km/h)'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2],
      dtype=int64)

In [38]:
df.count()

Date/Time             8784
Temp (C)              8784
Dew Point Temp (C)    8784
Rel Hum (%)           8784
Wind Spd (km/h)       8784
Visibility (km)       8784
Stn Press (kPa)       8784
Weather               8784
dtype: int64

In [39]:
df['Wind Spd (km/h)'].count()

8784

In [43]:
df['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Haze                                         16
Thunderstorms,Rain Showers                   16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Moderate Snow                                 4
Freezing Fog                                  4
Snow Showers,Fog                              4
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Thunderstorms,Rain Showers,Fog                3
Rain,Haze                                     3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Rain Showers,Snow Showers                     2
Freezing Rain,Snow Grains                     1
Rain,Snow,Fog                                 1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Heavy Rain Showers              1
Thunderstorms,Rain,Fog                        1
Freezing Rain,Ice Pellets,Fog                 1
Snow Pellets                                  1
Rain,Ice Pellets                              1
Moderate Rain,Fog                             1
Rain Showers,Fog                              1
Drizzle,Ice Pellets,Fog                       1
Rain,Snow Grains                              1
Name: Weather, dtype: int64

In [42]:
type(df['Weather'].value_counts())

pandas.core.series.Series

In [48]:
df['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Haze                                         16
Thunderstorms,Rain Showers                   16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Moderate Snow                                 4
Freezing Fog                                  4
Snow Showers,Fog                              4
Thunderstorms,Rain                            3
Freezing Drizzle,Haze                         3
Thunderstorms,Rain Showers,Fog                3
Rain,Haze                                     3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Moderate Snow,Blowing Snow                    2
Thunderstorms                                 2
Rain Showers,Snow Showers                     2
Freezing Rain,Snow Grains                     1
Rain,Snow,Fog                                 1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Heavy Rain Showers              1
Thunderstorms,Rain,Fog                        1
Freezing Rain,Ice Pellets,Fog                 1
Snow Pellets                                  1
Rain,Ice Pellets                              1
Moderate Rain,Fog                             1
Rain Showers,Fog                              1
Drizzle,Ice Pellets,Fog                       1
Rain,Snow Grains                              1
Name: Weather, dtype: int64

In [51]:
s= df['Weather'].value_counts()

In [52]:
s.index

Index(['Mainly Clear', 'Mostly Cloudy', 'Cloudy', 'Clear', 'Snow', 'Rain',
       'Rain Showers', 'Fog', 'Rain,Fog', 'Drizzle,Fog', 'Snow Showers',
       'Drizzle', 'Snow,Fog', 'Snow,Blowing Snow', 'Rain,Snow', 'Haze',
       'Thunderstorms,Rain Showers', 'Drizzle,Snow,Fog', 'Freezing Rain',
       'Freezing Drizzle,Snow', 'Freezing Drizzle', 'Snow,Ice Pellets',
       'Freezing Drizzle,Fog', 'Snow,Haze', 'Rain,Snow,Ice Pellets',
       'Freezing Rain,Fog', 'Moderate Snow', 'Freezing Fog',
       'Snow Showers,Fog', 'Thunderstorms,Rain', 'Freezing Drizzle,Haze',
       'Thunderstorms,Rain Showers,Fog', 'Rain,Haze', 'Freezing Rain,Haze',
       'Drizzle,Snow', 'Moderate Snow,Blowing Snow', 'Thunderstorms',
       'Rain Showers,Snow Showers', 'Freezing Rain,Snow Grains',
       'Rain,Snow,Fog', 'Thunderstorms,Moderate Rain Showers,Fog',
       'Thunderstorms,Heavy Rain Showers', 'Thunderstorms,Rain,Fog',
       'Freezing Rain,Ice Pellets,Fog', 'Snow Pellets', 'Rain,Ice Pellets',
       'Moderate Rain,Fog', 'Rain Showers,Fog', 'Drizzle,Ice Pellets,Fog',
       'Rain,Snow Grains'],
      dtype='object')

In [46]:
df['Weather'].value_counts().index

Index(['Mainly Clear', 'Mostly Cloudy', 'Cloudy', 'Clear', 'Snow', 'Rain',
       'Rain Showers', 'Fog', 'Rain,Fog', 'Drizzle,Fog', 'Snow Showers',
       'Drizzle', 'Snow,Fog', 'Snow,Blowing Snow', 'Rain,Snow', 'Haze',
       'Thunderstorms,Rain Showers', 'Drizzle,Snow,Fog', 'Freezing Rain',
       'Freezing Drizzle,Snow', 'Freezing Drizzle', 'Snow,Ice Pellets',
       'Freezing Drizzle,Fog', 'Snow,Haze', 'Rain,Snow,Ice Pellets',
       'Freezing Rain,Fog', 'Moderate Snow', 'Freezing Fog',
       'Snow Showers,Fog', 'Thunderstorms,Rain', 'Freezing Drizzle,Haze',
       'Thunderstorms,Rain Showers,Fog', 'Rain,Haze', 'Freezing Rain,Haze',
       'Drizzle,Snow', 'Moderate Snow,Blowing Snow', 'Thunderstorms',
       'Rain Showers,Snow Showers', 'Freezing Rain,Snow Grains',
       'Rain,Snow,Fog', 'Thunderstorms,Moderate Rain Showers,Fog',
       'Thunderstorms,Heavy Rain Showers', 'Thunderstorms,Rain,Fog',
       'Freezing Rain,Ice Pellets,Fog', 'Snow Pellets', 'Rain,Ice Pellets',
       'Moderate Rain,Fog', 'Rain Showers,Fog', 'Drizzle,Ice Pellets,Fog',
       'Rain,Snow Grains'],
      dtype='object')

In [49]:
df['Weather'].value_counts().values

array([2106, 2069, 1728, 1326,  390,  306,  188,  150,  116,   80,   60,
         41,   37,   19,   18,   16,   16,   15,   14,   11,    7,    6,
          6,    5,    4,    4,    4,    4,    4,    3,    3,    3,    3,
          2,    2,    2,    2,    2,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1], dtype=int64)

#### Question: Find the number of times when the weather was exactly clear.

In [53]:
df['Weather'].value_counts()['Clear']

1326

#### Question: Find the number of times the wind speed was exactly 4 km/hr.

In [54]:
df['Wind Spd (km/h)'].value_counts()

9     830
11    791
13    735
15    719
7     677
17    666
19    616
6     609
20    496
4     474
22    439
24    374
0     309
26    242
28    205
30    161
32    139
33     85
35     53
37     45
39     24
41     22
44     14
43     13
48     13
46     11
52      7
57      5
50      4
2       2
63      1
54      1
70      1
83      1
Name: Wind Spd (km/h), dtype: int64

In [55]:
df['Wind Spd (km/h)'].value_counts()[4]

474

In [56]:
df.loc[:,['Weather','Temp (C)']]

                   Weather  Temp (C)
0                      Fog      -1.8
1                      Fog      -1.8
2     Freezing Drizzle,Fog      -1.8
3     Freezing Drizzle,Fog      -1.5
4                      Fog      -1.5
...                    ...       ...
8779                  Snow       0.1
8780                  Snow       0.2
8781                  Snow      -0.5
8782                  Snow      -0.2
8783                  Snow       0.0

[8784 rows x 2 columns]

In [1]:
##Return first 25 rows.

In [59]:
df.loc[:25]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,2012-01-01 05:00:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,2012-01-01 06:00:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,2012-01-01 07:00:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,2012-01-01 08:00:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,2012-01-01 09:00:00,-1.3,-3.1,88,15,4.0,101.20,Fog
10,2012-01-01 10:00:00,-1.0,-2.3,91,9,1.2,101.15,Fog
11,2012-01-01 11:00:00,-0.5,-2.1,89,7,4.0,100.98,Fog
12,2012-01-01 12:00:00,-0.2,-2.0,88,9,4.8,100.79,Fog
13,2012-01-01 13:00:00,0.2,-1.7,87,13,4.8,100.58,Fog
14,2012-01-01 14:00:00,0.8,-1.1,87,20,4.8,100.31,Fog
15,2012-01-01 15:00:00,1.8,-0.4,85,22,6.4,100.07,Fog
16,2012-01-01 16:00:00,2.6,-0.2,82,13,12.9,99.93,Mostly Cloudy
17,2012-01-01 17:00:00,3.0,0.0,81,13,16.1,99.81,Cloudy
18,2012-01-01 18:00:00,3.8,1.0,82,15,12.9,99.74,Rain
19,2012-01-01 19:00:00,3.1,1.3,88,15,12.9,99.68,Rain
20,2012-01-01 20:00:00,3.2,1.3,87,19,25.0,99.50,Cloudy
21,2012-01-01 21:00:00,4.0,1.7,85,20,25.0,99.39,Cloudy
22,2012-01-01 22:00:00,4.4,1.9,84,24,19.3,99.32,Rain Showers
23,2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,2012-01-02 01:00:00,4.6,0.0,72,39,25.0,99.26,Cloudy

In [60]:
df[:25]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,2012-01-01 05:00:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,2012-01-01 06:00:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,2012-01-01 07:00:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,2012-01-01 08:00:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,2012-01-01 09:00:00,-1.3,-3.1,88,15,4.0,101.20,Fog
10,2012-01-01 10:00:00,-1.0,-2.3,91,9,1.2,101.15,Fog
11,2012-01-01 11:00:00,-0.5,-2.1,89,7,4.0,100.98,Fog
12,2012-01-01 12:00:00,-0.2,-2.0,88,9,4.8,100.79,Fog
13,2012-01-01 13:00:00,0.2,-1.7,87,13,4.8,100.58,Fog
14,2012-01-01 14:00:00,0.8,-1.1,87,20,4.8,100.31,Fog
15,2012-01-01 15:00:00,1.8,-0.4,85,22,6.4,100.07,Fog
16,2012-01-01 16:00:00,2.6,-0.2,82,13,12.9,99.93,Mostly Cloudy
17,2012-01-01 17:00:00,3.0,0.0,81,13,16.1,99.81,Cloudy
18,2012-01-01 18:00:00,3.8,1.0,82,15,12.9,99.74,Rain
19,2012-01-01 19:00:00,3.1,1.3,88,15,12.9,99.68,Rain
20,2012-01-01 20:00:00,3.2,1.3,87,19,25.0,99.50,Cloudy
21,2012-01-01 21:00:00,4.0,1.7,85,20,25.0,99.39,Cloudy
22,2012-01-01 22:00:00,4.4,1.9,84,24,19.3,99.32,Rain Showers
23,2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers

In [61]:
df.head(25)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,2012-01-01 05:00:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,2012-01-01 06:00:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,2012-01-01 07:00:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,2012-01-01 08:00:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,2012-01-01 09:00:00,-1.3,-3.1,88,15,4.0,101.20,Fog
10,2012-01-01 10:00:00,-1.0,-2.3,91,9,1.2,101.15,Fog
11,2012-01-01 11:00:00,-0.5,-2.1,89,7,4.0,100.98,Fog
12,2012-01-01 12:00:00,-0.2,-2.0,88,9,4.8,100.79,Fog
13,2012-01-01 13:00:00,0.2,-1.7,87,13,4.8,100.58,Fog
14,2012-01-01 14:00:00,0.8,-1.1,87,20,4.8,100.31,Fog
15,2012-01-01 15:00:00,1.8,-0.4,85,22,6.4,100.07,Fog
16,2012-01-01 16:00:00,2.6,-0.2,82,13,12.9,99.93,Mostly Cloudy
17,2012-01-01 17:00:00,3.0,0.0,81,13,16.1,99.81,Cloudy
18,2012-01-01 18:00:00,3.8,1.0,82,15,12.9,99.74,Rain
19,2012-01-01 19:00:00,3.1,1.3,88,15,12.9,99.68,Rain
20,2012-01-01 20:00:00,3.2,1.3,87,19,25.0,99.50,Cloudy
21,2012-01-01 21:00:00,4.0,1.7,85,20,25.0,99.39,Cloudy
22,2012-01-01 22:00:00,4.4,1.9,84,24,19.3,99.32,Rain Showers
23,2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers

In [ ]:
# Question: Get 3 alternating rows , but only columns visibility and relative humidity.

Multiple methods to do the same are listed below.

In [62]:
df.loc[range(0,6,2),['Visibility (km)','Rel Hum (%)']]

   Visibility (km)  Rel Hum (%)
0              8.0           86
2              4.0           89
4              4.8           88

In [65]:
df.loc[0:4:2,['Visibility (km)','Rel Hum (%)']]

   Visibility (km)  Rel Hum (%)
0              8.0           86
2              4.0           89
4              4.8           88

In [66]:
df.iloc[0:4,4]

0    4
1    4
2    7
3    6
Name: Wind Spd (km/h), dtype: int64

In [13]:
df['Weather'].str[0]

0       F
1       F
2       F
3       F
4       F
       ..
8779    S
8780    S
8781    S
8782    S
8783    S
Name: Weather, Length: 8784, dtype: object

In [14]:
df['Weather'].dtypes

dtype('O')

In [19]:
list(df['Weather'])[3:10]

['Freezing Drizzle,Fog', 'Fog', 'Fog', 'Fog', 'Fog', 'Fog', 'Fog']

In [20]:
df['Weather'].str

In [23]:
df['Weather'].str

In [24]:
df['Weather'].str.lower()

0                        fog
1                        fog
2       freezing drizzle,fog
3       freezing drizzle,fog
4                        fog
                ...
8779                    snow
8780                    snow
8781                    snow
8782                    snow
8783                    snow
Name: Weather, Length: 8784, dtype: object

In [25]:
df['Weather'].str.lower().contains('snow')

AttributeError: 'Series' object has no attribute 'contains'

In [27]:
df['Weather'].str.lower().str.contains('snow')

0       False
1       False
2       False
3       False
4       False
        ...
8779     True
8780     True
8781     True
8782     True
8783     True
Name: Weather, Length: 8784, dtype: bool

In [28]:
# Question: Find all instances when snow was recorded

In [29]:
df.loc[ df['Weather'].str.lower().str.contains('snow') ]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
41,2012-01-02 17:00:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,2012-01-02 20:00:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,2012-01-02 21:00:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,2012-01-02 23:00:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,2012-01-03 00:00:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [30]:
# Question: Find all instances where the wind speed was above 24 and visibility was 25

In [32]:
df.loc[(df['Wind Spd (km/h)']>24) & (df['Visibility (km)']==25)]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
23,2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,2012-01-02 01:00:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,2012-01-02 02:00:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,2012-01-02 03:00:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,2012-12-28 17:00:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,2012-12-30 17:00:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,2012-12-30 19:00:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,2012-12-30 23:00:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,2012-12-31 00:00:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

In [6]:
df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [7]:
df['Wind Spd (km/h)']*2

0        8
1        8
2       14
3       12
4       14
        ..
8779    60
8780    48
8781    56
8782    56
8783    60
Name: Wind Spd (km/h), Length: 8784, dtype: int64

In [8]:
df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [12]:
def mult(a):
    return a*2
df['Wind Spd (km/h)'].apply(mult)

0        8
1        8
2       14
3       12
4       14
        ..
8779    60
8780    48
8781    56
8782    56
8783    60
Name: Wind Spd (km/h), Length: 8784, dtype: int64

In [10]:
df

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [53]:
df.sort_values('Rel Hum (%)',ascending=False).value_counts()

Series([], dtype: int64)

In [52]:
s

NameError: name 's' is not defined

In [71]:
df.sort_values('Rel Hum (%)',ascending = False)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
6629,2012-10-03 05:00:00,None,11.0,100,11,3.2,101.38,Fog
6630,2012-10-03 06:00:00,None,11.5,100,11,0.6,101.42,Fog
1834,2012-03-17 10:00:00,None,2.6,100,0,0.2,102.37,Fog
8083,2012-12-02 19:00:00,None,5.9,100,15,3.6,100.67,"Drizzle,Fog"
6668,2012-10-04 20:00:00,None,14.1,100,4,9.7,101.10,Fog
...,...,...,...,...,...,...,...,...
3058,2012-05-07 10:00:00,None,-5.9,20,13,48.3,101.67,Clear
3065,2012-05-07 17:00:00,None,-2.9,20,13,48.3,101.07,Mostly Cloudy
1982,2012-03-23 14:00:00,None,-6.8,19,15,48.3,101.66,Mostly Cloudy
1984,2012-03-23 16:00:00,None,-9.0,18,22,48.3,101.60,Cloudy
3066,2012-05-07 18:00:00,None,-4.4,18,13,48.3,101.00,Mostly Cloudy

In [72]:
df     # not updated in the original df. now we will try using inplace method.

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
4695,2012-07-14 15:00:00,None,16.8,38,22,48.3,101.31,Mainly Clear
4143,2012-06-21 15:00:00,None,19.0,44,24,24.1,100.20,Mainly Clear
4696,2012-07-14 16:00:00,None,15.3,35,24,48.3,101.26,Mainly Clear
5199,2012-08-04 15:00:00,None,18.8,44,17,24.1,101.39,Clear
4694,2012-07-14 14:00:00,None,15.3,35,28,48.3,101.35,Mainly Clear
...,...,...,...,...,...,...,...,...
338,2012-01-15 02:00:00,None,-26.6,63,9,25.0,101.99,Cloudy
345,2012-01-15 09:00:00,None,-27.8,60,9,48.3,102.57,Mainly Clear
343,2012-01-15 07:00:00,None,-28.0,62,9,25.0,102.37,Mainly Clear
342,2012-01-15 06:00:00,None,-28.5,62,7,25.0,102.28,Mostly Cloudy
344,2012-01-15 08:00:00,None,-28.5,62,7,24.1,102.45,Clear

In [74]:
df.sort_values('Rel Hum (%)',ascending = False, inplace= True)

In [68]:
df1 = df.sort_values('Rel Hum (%)',ascending = False)

In [69]:
df1

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
6629,2012-10-03 05:00:00,None,11.0,100,11,3.2,101.38,Fog
6630,2012-10-03 06:00:00,None,11.5,100,11,0.6,101.42,Fog
1834,2012-03-17 10:00:00,None,2.6,100,0,0.2,102.37,Fog
8083,2012-12-02 19:00:00,None,5.9,100,15,3.6,100.67,"Drizzle,Fog"
6668,2012-10-04 20:00:00,None,14.1,100,4,9.7,101.10,Fog
...,...,...,...,...,...,...,...,...
3058,2012-05-07 10:00:00,None,-5.9,20,13,48.3,101.67,Clear
3065,2012-05-07 17:00:00,None,-2.9,20,13,48.3,101.07,Mostly Cloudy
1982,2012-03-23 14:00:00,None,-6.8,19,15,48.3,101.66,Mostly Cloudy
1984,2012-03-23 16:00:00,None,-9.0,18,22,48.3,101.60,Cloudy
3066,2012-05-07 18:00:00,None,-4.4,18,13,48.3,101.00,Mostly Cloudy

In [70]:
df1['Rel Hum (%)'].value_counts()

68    210
83    202
81    195
71    194
64    192
     ...
22      6
23      5
20      5
18      2
19      1
Name: Rel Hum (%), Length: 83, dtype: int64

In [65]:
df['Rel Hum (%)'].sort_values(ascending= False)

6606    100
7038    100
6629    100
6668    100
8083    100
       ...
3067     20
3065     20
1982     19
1984     18
3066     18
Name: Rel Hum (%), Length: 8784, dtype: int64

In [64]:
type(df['Rel Hum (%)'].sort_values(ascending= False))

pandas.core.series.Series

In [60]:
s = df['Rel Hum (%)'].sort_values(ascending= False)

6606    100
7038    100
6629    100
6668    100
8083    100
       ...
3067     20
3065     20
1982     19
1984     18
3066     18
Name: Rel Hum (%), Length: 8784, dtype: int64

In [58]:
s.head(10)

68    210
83    202
81    195
71    194
64    192
59    192
82    185
63    184
65    184
70    181
Name: Rel Hum (%), dtype: int64